name: Deploy MeetApp app

on:
  push:
    branches:
      - dev

env:
  VITE_APP_URL: '/meetups-mp-full-stack/'
permissions:
  contents: read
  packages: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Modules
        run: npm install
        working-directory: ./meetups-front-end
      - name: Build
        run: npm run build-dev
        working-directory: ./meetups-front-end
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: './meetups-front-end/dist'
      - name: Deploy to github pages
        uses: actions/deploy-pages@v1

      - name: Deploy React app
        id: deployment
        uses: actions/deploy-pages@v1
